"""empty message

Revision ID: bf986cbd73f5
Revises: 0fbb4b006a2d
Create Date: 2024-12-23 20:14:54.509935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf986cbd73f5'
down_revision = '0fbb4b006a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'powerplant', ['plant_id'], ['id'])

    with op.batch_alter_table('powerplant', schema=None) as batch_op:
        batch_op.drop_constraint('powerplant_generator_id_fkey', type_='foreignkey')
        batch_op.drop_column('generator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powerplant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('powerplant_generator_id_fkey', 'generator', ['generator_id'], ['id'])

    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
